# -*- coding: utf-8 -*-
"""Movie Recommendation System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1isTTBHqv8bpJ8FuFldM5zssJ7QctvnJu
"""

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import difflib

from google.colab import drive
drive.mount('/content/drive')

movie_data = pd.read_csv('/content/drive/MyDrive/movies.csv')

movie_data.head()

movie_data.shape

movie_data.isnull().sum()

#selecte the important features for our project
selected_feature = ['genres','keywords','tagline','cast','director']

print (selected_feature)

#fill the nulls in mt selected
for features in selected_feature:
  movie_data[features] = movie_data[features].fillna('')

print ( selected_feature)

#make a combination with my selected feature to conver it to numbers
combined_feature = movie_data['genres']+' '+ movie_data['keywords']+' '+movie_data['tagline']+' '+movie_data['cast']+' '+movie_data['director']

print (combined_feature)

vectorizer = TfidfVectorizer()

#converte the data to numbers to train the model
feature_vectorized= vectorizer.fit_transform(combined_feature)

print (feature_vectorized)

#find the similarity between data
similarity = cosine_similarity(feature_vectorized)

print (similarity)

print (similarity.shape)

selected_movie = input("please enter the movie name: ")

list_of_all_titles= movie_data['title'].tolist()

print (list_of_all_titles)

#print relevante movies
relevante_movie = difflib.get_close_matches(selected_movie , list_of_all_titles)

print (relevante_movie)

close_match= relevante_movie[-1]

print(close_match)

index_of_the_movie=movie_data[movie_data.title==close_match]['index'].values[0]

print (index_of_the_movie)

similarity_score= list(enumerate(similarity[index_of_the_movie]))

print (similarity_score)

sorted_movie=sorted(similarity_score , key=lambda x:x[1],reverse=True)

print(sorted_movie)

print("movies sugessted for you  : ")
i=0
for movie in sorted_movie:
  index  = movie[0]
  title_from_index = movie_data[movie_data.index==index]['title'].values
  if (i<31):
    print(i,'=>',title_from_index)
    i+=1

"""Movie Recommendation system

"""

selected_movie = input("please enter the movie name: ")
list_of_all_titles= movie_data['title'].tolist()
relevante_movie = difflib.get_close_matches(selected_movie , list_of_all_titles)
close_match= relevante_movie[0]
index_of_the_movie=movie_data[movie_data.title==close_match]['index'].values[0]
similarity_score= list(enumerate(similarity[index_of_the_movie]))
sorted_movie=sorted(similarity_score , key=lambda x:x[1],reverse=True)
print ("movies sugestted for you : ")
i=0
i=0
for movie in sorted_movie:
  index  = movie[0]
  title_from_index = movie_data[movie_data.index==index]['title'].values
  if (i<31):
    print(i,'=>',title_from_index)
    i+=1

# Choose first 20 movies for visualization
subset_similarity = similarity[:20, :20]
subset_titles = movie_data['title'].head(20)

plt.figure(figsize=(14, 10))
sns.heatmap(subset_similarity, xticklabels=subset_titles, yticklabels=subset_titles, cmap="viridis")
plt.title("Movie Similarity Matrix Heatmap (Top 20 Movies)")
plt.xticks(rotation=90)
plt.show()

selected_movie = "iron man "   # <- you can replace with user input

# Find best title match
list_of_all_titles = movie_data['title'].tolist()
relevant_movie = difflib.get_close_matches(selected_movie, list_of_all_titles)
close_match = relevant_movie[0]

movie_index = movie_data[movie_data.title == close_match].index[0]

# Calculate similarity scores and sort
similarity_score = list(enumerate(similarity[movie_index]))
sorted_movies = sorted(similarity_score, key=lambda x: x[1], reverse=True)

top_10 = sorted_movies[1:11]  # skip itself (index 0)

rec_titles = [movie_data.iloc[i[0]].title for i in top_10]
rec_scores = [i[1] for i in top_10]

plt.figure(figsize=(12, 6))
sns.barplot(x=rec_scores, y=rec_titles)
plt.title(f"Top 10 Recommendations for '{close_match}'")
plt.xlabel("Similarity Score")
plt.ylabel("Recommended Movies")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# ---- COSINE SIMILARITY VISUALIZATION (TOP 20 MOVIES) ---- #

# Select the first 20 movies for visualization
similarity_subset = similarity[:20, :20]

movie_titles = movie_data['title'].head(20).tolist()

plt.figure(figsize=(14, 10))
sns.heatmap(similarity_subset,
            xticklabels=movie_titles,
            yticklabels=movie_titles,
            cmap="coolwarm",
            square=True)

plt.title("Cosine Similarity Heatmap (Top 20 Movies)")
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

